// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace JwtTutorial.Models.Entities
{
    public partial class Tag
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}